# fly.toml app configuration file generated for ams-birthday-bot on 2023-09-13T22:41:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ams-birthday-bot"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
